version: 0.2
env:
 parameter-store:
   JASYPT_PASSWORD: "my_password" 
   

phases:
  pre_build:
   commands:
     - echo "maven build"
     - mvn clean install -Djasypt.encryptor.password=$JASYPT_PASSWORD
     - echo "Loggin into Aamzon ECR"
     - ECR_REPO_URL=733537661031.dkr.ecr.ap-south-1.amazonaws.com/simple-docker-service-06f5939b5509 
     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REPO_URL
     - echo "Setting image tag"
     - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
     - IMAGE_TAG=${COMMIT_HASH:=latest}
  
  build:
   commands:
     - echo "Building docker image"
     - docker build -t $ECR_REPO_URL:$IMAGE_TAG .
     - docker tag $ECR_REPO_URL:$IMAGE_TAG $ECR_REPO_URL:latest
     - echo "docker build completed"
  
  post_build:
   commands:
     - echo "Puhsing docker build into $ECR_REPO_URL"
     - echo docker push $ECR_REPO_URL:$IMAGE_TAG
     - docker push $ECR_REPO_URL:$IMAGE_TAG
     - echo docker push $ECR_REPO_URL:latest
     - docker push $ECR_REPO_URL:latest
     - echo "writing image definitions file.."
     - printf '[{"name":"pay_roll_service","imageUri":"%s"}]' $ECR_REPO_URL:$IMAGE_TAG > imagedefinitions.json
     - cat imagedefinitions.json
  
artifacts:
  files:
   - imagedefinitions.json    
