name: Deploy Spring boot on EC2 Instance

on:
  push:
    branches:
      mem_database
  commit:
    branches:
      mem_database
      
jobs:
 build:
  runs-on: ubuntu-latest
  
  steps:
  - name: checkout code
    uses: action/checkout@v4
    run: echo "Hello..."
